version: "3.9"
services:
  default:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - share_volume:/share:rw
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  share_volume:
    external: true
    name: share
